name: LabSTFT
dependencies:
  - python==3.6.5
  - numpy==1.13.3
  - scipy==1.0.0
  - matplotlib==2.0.2
  - jupyter==1.0.0
  - pandoc==2.2.3.2
  - pip:
    - pysoundfile==0.9.0.post1
    - librosa==0.6.1
